### ISSUE TITLE
Powerline Icons are too small

### ISSUE THREAD

**Issue by darookee** [ryanoasis/nerd-fonts#26]
Using mintty, the screenshot shows "Meslo LG S DZ" but the other "Meslo"-fonts, "Droid Sans Mono", "Bitstream Vera Sans Mono" and "DejaVu Sans Mono" also look like this.

![powerline-icons-too-small](https://cloud.githubusercontent.com/assets/104579/9576691/60b69a92-4fda-11e5-99c8-34cd7c63c8a2.PNG)

**Comment by karlmutch** [comment]
I have this occurring on xft based rendering as well, using urxvt. It only seems to occur with the powerline glyphs

**Comment by ryanoasis** [comment]
I've been away but I will look into this when back. 

@darookee I will have to try things out on Windows in term emulators.

@karlmutch I was able to get it working for me on urxvt. Can you share your config settings?

I have: 
`URxvt.font: xft:Droid Sans Mono for Powerline Plus Nerd File Types Mono:pixelsize=16:antialias=true:hinting=true`

**Comment by lotrfan** [comment]
I'm getting it (on urxvt) with

```
urxvt.font:               xft:Meslo LG S DZ for Powerline Plus Nerd File Types Mono:pixelsize=14
```
(as well as a bunch of other Meslo variations)

Droid sans (`urxvt.font: xft:Droid Sans Mono for Powerline Plus Nerd File Types Mono:pixelsize=14`) also has the issue, but others (Inconsolata and Anonymous Pro were the ones I noticed) are fine.

**Comment by lotrfan** [comment]
that was off of master (6158e08) with a [semi-patched](https://aur.archlinux.org/packages/rxvt-unicode-patched/) version of urxvt 9.21

**Comment by karlmutch** [comment]
I had urxvt 1.19 and replicated the same using Droid Sans Mono will see
what happens when using the 2 fonts you mentioned worked.

**Comment by ShiroiKuma** [comment]
Excellent work, but as darookee says. DejaVu Sans Mono PowerLine symbols are too small. I can't find any other issues, just those. Using mintty here too.

**Comment by kiranps** [comment]
@ShiroiKuma there are small and big powerline symbols .you must have tried smal one . try this  ⮀  ⮂

**Comment by ShiroiKuma** [comment]
Oh okay. I'm using UxE0B0 and UxE0B1 in my prompt. I'll look for other codes.

**Comment by iravid** [comment]
I'm also seeing glyph size anomalies, but on OS X using iTerm and Anonymous Pro. Screenshots:

This was taken using the pre-patched font from the repository:
![image](https://cloud.githubusercontent.com/assets/283332/9872052/72ca519e-5b9f-11e5-9b91-8cd7bf6d2b0d.png)

The arrow glyphs are E0B0 - E0B3.

You can also see that E0A0 is abnormally small:
![image](https://cloud.githubusercontent.com/assets/283332/9872100/c8d2c1d4-5b9f-11e5-8b16-8a04305bd0b3.png)

The version from powerline/fonts (Anonymous Pro for Powerline) doesn't have these issues:
![image](https://cloud.githubusercontent.com/assets/283332/9872150/162b9d48-5ba0-11e5-83e3-d26cbca2c72c.png)
![image](https://cloud.githubusercontent.com/assets/283332/9872159/24029386-5ba0-11e5-94ad-5d9a6c978019.png)


Inconsolata for Powerline Plus Nerd File Types doesn't have this issue either, but has the strange spacing that was described in #29:
![image](https://cloud.githubusercontent.com/assets/283332/9872208/677e901a-5ba0-11e5-88b9-93462becb2b6.png)
![image](https://cloud.githubusercontent.com/assets/283332/9872214/739194a6-5ba0-11e5-8ec9-641141fe15bd.png)

**Comment by darookee** [comment]
I compared both fonts using the Symboltable in Windows. The first one is DejaVu Sans Mono from the powerline repository:
![powerline](https://cloud.githubusercontent.com/assets/104579/9872467/d09a5b8a-5b99-11e5-8d30-f27ce84f9119.PNG)

The second the one from nerd-fonts
![nerd](https://cloud.githubusercontent.com/assets/104579/9872468/d0b26c3e-5b99-11e5-85fe-d888a286bf32.PNG)

**Comment by dritter** [comment]
I have the same Issue on OSX yosemite with iTerm2. I used "Droid Sans Mono for Powerline Plus Nerd File Types Plus Font Awesome Plus Octicons". So this is no windows-only problem..

**Comment by ryanoasis** [comment]
Thanks for all the info I think it will help. :)

**Comment by DanielGGordon** [comment]
- DejaVu Sans Mono
- Meslo LG M
- Droid Sans
- Anonymice

I tried these 4x, and didn't see such small icons. Although the icons are a **bit** small. It's not dramatic, but because they are monotyped for Mintty compatibility, sometimes the icons just don't look as good in Windows.

**Comment by ryanoasis** [comment]
@DanielGGordon Awesome! Thanks for the detailed report and feedback. It will prove helpful :tada: 

Yeah getting things to look right with fonts can be a huge pain :worried:

**Comment by kierun** [comment]
I am getting the same effect when trying to patch the PragmataPro font set:

![screenshot](https://cloud.githubusercontent.com/assets/3079575/17764866/188610bc-651a-11e6-84ba-11660536b358.png)

**Comment by ryanoasis** [comment]
@kierun Thanks yeah that looks really bad. I am going to try to really get back into fixing some of these serious issues.

**Comment by kierun** [comment]
[This `neovim-qt` issue may or may not have some bearing on how I see font…](https://github.com/equalsraf/neovim-qt/issues/164)

**Comment by ryanoasis** [comment]
I believe small powerline glyphs should at least be fixed in the latest version but I will test urxvt in particular with the menttioned fonts and if it goes well I will close this issue

**Comment by nomoon** [comment]
I'm still having some issues with my Powerline glyph sizes in iTerm.

DejaVuSansMonoforPowerline Nerd Font (complete)
<img width="777" alt="screen shot 2017-03-03 at 03 32 17" src="https://cloud.githubusercontent.com/assets/593185/23549644/0d163f8e-ffc2-11e6-9497-c703c3689202.png">
vs DejaVu Sans Mono for Powerline
<img width="777" alt="screen shot 2017-03-03 at 03 33 19" src="https://cloud.githubusercontent.com/assets/593185/23549705/553761ee-ffc2-11e6-8c75-a704bdb8a110.png">

**Comment by ryanoasis** [comment]
@nomoon Thanks for the details. Looks more like an alignment issue than size issue?

Btw, I like your prompt. Where is it from? :blush:

**Comment by nomoon** [comment]
@ryanoasis that's powerlevel9k, which is in the process of rolling out nerd font support. I do think there's a bit of a sizing issue, though. The powerline arrows typically protrude a bit at the bottom.

**Comment by ryanoasis** [comment]
@nomoon Ah I should have realized it was PL9K. Yeah I have been kind of following along with the developments :smile: 

> The powerline arrows typically protrude a bit at the bottom

Working on a test script that will help us test sizing and alignment issues more easily

**Comment by SirDoctors** [comment]
I'm noticing the same thing as @nomoon, however It only appears with knack nerd font regular & driodsansmonoforpowerline nerd font book... but not with furamonoforpowerline nerd font regular

**Comment by voiprodrigo** [comment]
Hi,

I seem to have a related issue. I'm using nerd-fonts with p9k, OS X iterm2 

I see one-pixel gaps between the segments on the right, but not on the left:

![screen shot 2017-03-09 at 18 47 33](https://cloud.githubusercontent.com/assets/2421504/23765379/f1779ba6-04f8-11e7-9911-f43bd37658a5.png)

I'm using 14pt Meslo LG M Regular for Powerline Nerd Font Complete in iTerm2 profile.
Problem goes away if I use regular Meslo Powerline version (but I lose the additional icons)

rgds.

**Comment by ryanoasis** [comment]
@SirDoctors and @voiprodrigo Thanks for the details.

So I think I would need to test the original (unpatched sources of these fonts) unless either of you can do that as well (the ones included in this repo [here](https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts)).

Some of these fonts we have a config (`config_has_powerline`) where if present the patcher _should_ not touch or attempt to patch the powerline glyphs but instead use the ones provided by the source font.

That's why I want to check the source fonts to see if they have the same gap issues.

**Comment by nomoon** [comment]
@ryanoasis I just downloaded both of the unpatched DejaVu Sans Mono & DejaVu Sans Mono for Powerline fonts, and they appear to work correctly. Only thing that I noticed is the regular "DejaVu Sans Mono" font file seems to already have the Powerline glyphs in it.

**Comment by SirDoctors** [comment]
I downloaded Hack and removed the nerd fonts patched version from my fonts cache ``fc-cache -f -r -v`` after selecting and reloading my terminal (gnome-terminal) and tmux I'm noticing this http://i.imgur.com/75vqVwG.png

**Comment by xasx** [comment]
My discovery is that if you use
* **Mono** variant:
   * you'll get _small icons_
   * but have _no gaps_ between the triangles
* **non-Mono** variant:
   * you get the _full-sized icons_ 
   * but _have gaps_ between the triangles

A typical 'you can't have one without the other'. :thinking:

**Comment by msva** [comment]
Depends on font.

Say, in Pragmata (it is monospaced by itself, but it also have `Mono` varint without ligatures) it is anyway 1px gap appears for "left-turned" triangles on *some* (!) font sizes.
And some icons is anyway small in both variants).

And this is much more sad, because I'd like to use `~9pt` size font in my terminal (having 271x75 Terminal on PragmataPro @ 9pt @ FullHD @ 96DPI), and `>=13pt` sizes on most fonts (including pragmata) are both **too big** and gives much less text space in terminal (especially, vertically). Although, bad side of this behaviour is that some devicons/awesome isons are too small to distinguish (either by design or because of patching/compilation issue) 😢 .

**Comment by ryanoasis** [comment]
So hopefully in 1.1 this will be as close to 'fixed' as possible.

## Here are some comparisons with Hack (Knack)

### current

![selection_025](https://cloud.githubusercontent.com/assets/8083459/24778118/e0180530-1af6-11e7-8b25-7515c9e2919c.png)

![selection_026](https://cloud.githubusercontent.com/assets/8083459/24778124/e781deb8-1af6-11e7-8f8a-37215e99e6dd.png)

![selection_027](https://cloud.githubusercontent.com/assets/8083459/24778129/eb53bad4-1af6-11e7-9ae0-ca6b0e510066.png)

### WIP (v1.1)

![selection_030](https://cloud.githubusercontent.com/assets/8083459/24778140/f97a0fc8-1af6-11e7-813b-49a3c8836091.png)

![selection_029](https://cloud.githubusercontent.com/assets/8083459/24778143/fcdce08c-1af6-11e7-8523-7d02ca20c233.png)

![selection_028](https://cloud.githubusercontent.com/assets/8083459/24778145/ffbf18ec-1af6-11e7-8426-aa5807e45a46.png)

---

@SirDoctors Are you saying you are seeing those gaps with `Hack` proper or with the patched `Nerd Fonts Knack` ?

---

@xasx Yes that is _mostly_ true:

> * **Mono** variant:
>    * you'll get _small icons_

Mono variant will always have 'small' icons because of the nature of monospaced they have to be that small to retain the scale or they would become stretched

> * **non-Mono** variant:
>    * you get the _full-sized icons_ 
>    * but _have gaps_ between the triangles

This is something v1.1 is targeting to fix.. along with some glyph alignment issues, and so far it is at least  looking _better_

**Comment by xasx** [comment]
> Mono variant will always have 'small' icons because of the nature of monospaced they have to be that small to retain the scale or they would become stretched

Don't get me wrong. I fully understand that it has to be like that with strictly-monospaced fonts and that it is the best way to offer terminals that only support monospaced fonts a way to incorporate the Nerd Fonts.

**Comment by ryanoasis** [comment]
@xasx No worries, apologies if I came across as if you didn't understand :smile: . Thanks for summarizing the current state in a clear way

**Comment by cemsbr** [comment]
> > Mono variant will always have 'small' icons because of the nature of monospaced they have to be that small to retain the scale or they would become stretched
> 
> Don't get me wrong. I fully understand that it has to be like that with strictly-monospaced fonts and that it is the best way to offer terminals that only support monospaced fonts a way to incorporate the Nerd Fonts.

For terminals that support double-width chars (i.e. Arch's rxvt-unicode-wcwidthcallback in AUR), using a non-nerd font with FontAwesome as fallback offers a better result. It would be nice to have the same with nerd fonts (not necessarily removing the strictly-monospaced fonts).

**Comment by ryanoasis** [comment]
@cemsbr If you are referring to a fallback option for Nerd Fonts that is possible with [this `fontconfig`](https://github.com/ryanoasis/nerd-fonts/blob/master/10-nerd-font-symbols.conf).

The font with just the symbols has yet to be uploaded to the repo (but one could take the config as-is and replace the symbol font with a patched font of their choosing).

Let me know if I misunderstood your 'would be nice to have' :blush:. Cheers

**Comment by cemsbr** [comment]
Sorry, I wasn't clear enough. I was using single-width fonts and found the double-width ones (non-nerdy :)) to be more readable. However, I've just searched for double-width in the readme and found that there's an option for the patcher to use single- or double-width. That's what I was looking for. Great work!

**Comment by ryanoasis** [comment]
@cemsbr Sure no problem! That's understandable, some of the information is probably still not very clear up front.

Heh this issue is getting pretty popular... I think I when I re-patch all the fonts in prep for v1.1.0 we can probably call this fixed :smile: :crossed_fingers:

**Comment by katylava** [comment]
In case it's not clear, this is also happening with Knack, but only with the glyphs in my right prompt.

![iterm](https://cloud.githubusercontent.com/assets/10575/26604094/cd06571c-454e-11e7-8639-2a94cb16471a.png)

**Comment by mavam** [comment]
I have the same issue as @katylava with the Meslo fonts:
<img width="378" alt="screen shot 2017-06-03 at 3 22 21 pm" src="https://cloud.githubusercontent.com/assets/53797/26753882/81870faa-4870-11e7-9847-b8d9bbc0b81b.png">

Top row: vim
Bottom row: tmux

**Comment by ryanoasis** [comment]
@katylava , @mavam First my apologies for the somewhat late response. I was about ready to say (and show) that this will be fixed in the next version (v1.1.0) when all the fonts are re-patched... however with the current code I am having some problems with it even building fonts that are detected by the OS. I suspect some py3 compat changes causing this... I haven't looked into it very deeply yet.

**Comment by ryanoasis** [comment]
@katylava @mavam 

Here is a comparison of the gaps:

### v1.0.0

![selection_011](https://user-images.githubusercontent.com/8083459/27263489-00689424-5438-11e7-91fd-569cd0a64dcd.png)


### v1.1.0 WIP

![selection_010](https://user-images.githubusercontent.com/8083459/27263488-fabcf81c-5437-11e7-89aa-bcdd69b04816.png)


You can see the gaps are almost entirely gone. I think this is a case where perfect is the enemy of good :smile: so we will build v1.1.0 as it appears here.

**Comment by pradyunsg** [comment]
Any sort of ETA on this? :3

**Comment by ryanoasis** [comment]
@pradyunsg Yep, actually I would say this weekend (either 5th or 6th August) as a part of [`v1.1.0` Release](https://github.com/ryanoasis/nerd-fonts/milestone/16)

**Comment by ryanoasis** [comment]
Fonts have been uploaded. Feel free to test them out. :smile: 

Closing this for now...

**Comment by mashehu** [comment]
I still have a gap at the right hand side prompt for the retina version of FuraCode (but it's fine for regular, etc.)

**Comment by CPWeaver** [comment]
@mashehu I saw the same thing, but it was size dependent. It looks really good to me though and much better! 

InputMono thin 12pt - small gap
<img width="18" alt="screen shot 2017-08-10 at 9 39 49 am" src="https://user-images.githubusercontent.com/4966467/29178846-00efe1d0-7db0-11e7-941a-1566a9bb83ec.png">

InputMono thin 13pt - no gap (although maybe 1px too short at the bottom?)
<img width="39" alt="screen shot 2017-08-10 at 9 39 59 am" src="https://user-images.githubusercontent.com/4966467/29178858-08930fa2-7db0-11e7-8dc1-03fe3847efa4.png">

I see the same thing with the pre-packaged fonts like sauce code pro.

**Comment by xasx** [comment]
I also see a minimally small gap when using Droid Sans Mono, at 11. It apparently turns red (probably depending on the color scheme) when I select 12. And there's no gap at 13 (but that's way too huge).

At 17, using Fura, the gap is super visible:

![bildschirmfoto von 2017-08-11 08-20-11](https://user-images.githubusercontent.com/1582730/29203036-f563658a-7e6d-11e7-9b75-053a7683a9b3.png)

I am wondering whether this still has something to do with the fonts themselves. Maybe OS/Theme/Terminal/whatever dependent rendering issue?

**Comment by pradyunsg** [comment]
@ryanoasis Thanks for the release! :tada: It's a major improvement over the previous versions. :)

That said, I believe you'd agree that the current patching still has a gap around the powerline symbols, albeit fairly small. 

Should there be a new Issue for that; since this issue of small size of the powerline symbols issue is fixed AFAICT.

**Comment by D4v2z** [comment]
Hi, I have the same problem with nerd-font (hack font regular Hack Regular Nerd Font Complete or Sauce Code Pro Nerd Font Complete). Tilix or Gnome-terminal.

![captura de pantalla de 2018-04-15 23-15-35](https://user-images.githubusercontent.com/26611092/38783578-27aa51a8-4104-11e8-91b2-b269510d41c9.png)

**Comment by RyRch** [comment]
HI, i have a problem im using i3 bumblebee bar and my "⮂" separator is smaller than the block and look bad any solutions of my problem ? :)
![desktop](https://user-images.githubusercontent.com/55916562/80980045-70c4c080-8e28-11ea-99c9-61ac43ea24ae.png)
