### ISSUE TITLE
Misalignment of Powerline Glyphs for Code New Roman Font Family

### ISSUE THREAD

**Issue by icp1994** [ryanoasis/nerd-fonts#296]
#### 🗹 Requirements

- 🗹 A brief but descriptive _title_ of your issue
- 🗹 I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- 🗹 I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- 🗹 I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

I have tried both the variations - double-width and single-width - but the glyph in the prompt seems to be out of alignment (image below for reference) . I don't have the issue with other patched fonts like Fantasque Sans Mono or Mononoki etc. I have also tried two different emulators (termite and alacritty) just to be sure. I didn't manually patch any of the fonts, just `curl`-ed them from the repo.

#### 🔧 Your Setup

- Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)? Code New Roman Nerd Font Complete.otf, Code New Roman Nerd Font Complete Mono.otf
- Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)? Termite, Alacritty
- Are you using OS X, Linux or Windows? And which specific version or distribution? Arch

#### ★ Optional

![2cusjqe](https://user-images.githubusercontent.com/15713555/46254863-9868df80-c4b3-11e8-9070-9933300d8c91.png)

**Comment by reaysawa** [comment]
I have this same issue on Tilix but no issues on Alacrity. Here is a side-by-side comparison:

![screenshot from 2018-10-17 19-20-59](https://user-images.githubusercontent.com/17429390/47119639-0f3b0200-d242-11e8-87c3-965e3c8a7851.png)

Notice how the symbols are are correctly aligned in **Alacritty** :arrow_left: and misaligned in :arrow_right: **Tilix**.

Font: Courier Prime Code patched with `--complete --adjust-line-height`
OS: Ubuntu Budgie 18.04

**Comment by reaysawa** [comment]
I have this same problem on Tilix, but it doesn't happen on Alacritty. Here is a side-by-side comparison:

![image](https://user-images.githubusercontent.com/17429390/47119929-40680200-d243-11e8-8c88-bf0d563bd236.png)

Notice how the symbols are are correctly aligned in **Alacritty** :arrow_left: and misaligned in 
:arrow_right: **Tilix**.

Font: Courier Prime Code patched with `--complete --adjust-line-height`
OS: Ubuntu Budgie 18.04

**Comment by ylmrx** [comment]
I'm having the same problem here. Sad, because it's the best looking font at most size (just my tastes).

**Comment by ryanoasis** [comment]
@icp1994 thanks for the report. Powerline characters are notorious for aligning

**Comment by KTibow** [comment]
Is this a dead repo? I'm experiencing the same thing 3 years later (Ubuntu, default terminal, Caskaydia Cove).

**Comment by Finii** [comment]
@KTibow  Well, this is fixed (at least for Caskaydia (*)) with #593. I guess it will be merged soon :grimacing:, won't it @ryanoasis?

The change is very small; if you can self-patch, maybe that is an option. Otherwise if you are solely interested in a patched Cascadia Code, there is https://github.com/adam7/delugia-code (which uses Nerd Font's `font-patcher` with #593 applied).

(*) I do not mention _Code New Roman_ in the PR, not sure it would fix that, it certainly looks similar, but maybe the metrics in the source font are not right.

**Comment by KTibow** [comment]
The original PL variant and Delugia seem to work better, other than one weird thing: The font size can create misalignment.
Here's what Delugia PL/Cascadia Code PL looks like at 12:
![image](https://user-images.githubusercontent.com/10727862/145679443-09bad6c7-3def-4a1f-8e02-78e07494a5be.png)
But at 10, I can see some misalignment (zoom in on the rounded corners):
![image](https://user-images.githubusercontent.com/10727862/145679464-43410cbb-fc6d-4b9e-97d8-bfd58f1b0352.png)

**Comment by Finii** [comment]
Ubu, gnome terminal (i guess)
Will check that. Probably rounding error.

**Comment by ryanoasis** [comment]
> Is this a dead repo?

No. Are you asking because of the number of unresolved issues?

> I'm experiencing the same thing 3 years later (Ubuntu, default terminal, Caskaydia Cove).
> @KTibow Well, this is fixed (at least for Caskaydia (*)) with #593

Yeah, I believe for at least Caskaydia this may/probably be fixed with you with the latest changes in `master` now.

> I guess it will be merged soon grimacing, won't it @ryanoasis?

Merged!

> (*) I do not mention Code New Roman in the PR, not sure it would fix that, it certainly looks similar, but maybe the metrics in the source font are not right.

Just tested this out and yeah it does not seem to make any improvement on that font in particular, as expected.

**Comment by KTibow** [comment]
I was just asking given the date the issue was opened. Anyway, it's fixed now.

**Comment by ryanoasis** [comment]
@KTibow okay great, sure.

This issue should remain open unfortunately, as Code New Roman problem still exists.

**Comment by Finii** [comment]
The fix just honors the 'we have correct metrics' flag that fonts can set.

_Code New Roman_ does not set it:
![image](https://user-images.githubusercontent.com/16012374/145713656-da07a519-e7bf-47c5-afda-6e4714f4ac1a.png)

So what we use is the guestimate mechanism. This needs some deeper dive into it. We could of course add an option to the config files, but that would not fix it for ad-hoc font-patcher use.

Need to punch in the numbers in a calculator and see why the guestimate is wrong.

**Comment by Finii** [comment]
Patched font:
![image](https://user-images.githubusercontent.com/16012374/145717924-ab57f767-0e3b-4467-ae3c-953c618b5b0e.png)

There is kind of a problem with the font - already in the sourcefont - that some letters are higher than the bounding box. Here in the example the `Ü` protrudes into the line above. The guesstimate accordingly centers the triangular stuff around that - too high - letters-space.

![image](https://user-images.githubusercontent.com/16012374/145718371-6b135712-89ff-4325-a2ab-55633c1fe6d8.png)

**Comment by Finii** [comment]
Ah, font patcher has an option for these fonts:

![image](https://user-images.githubusercontent.com/16012374/145719236-bc4f2c8a-41b4-436f-afca-105de812b75f.png)

It's all good if you specify `-l`:
```python
parser.add_argument('-l', '--adjust-line-height', [...]
help='Whether to adjust line heights (attempt to center powerline separators more evenly)')
```

It forces the WIN values (1884, -514) into HHEA (1521, -572, gap 350) but leaves the TYPO untouched?
And removes the gap, of course....
![image](https://user-images.githubusercontent.com/16012374/145719423-5a49de07-91d3-41ca-8058-eb1979464176.png)

There are several ways out of this... which need 'political' decisions :-D

**Comment by Finii** [comment]
Maybe @ryanoasis can remember why this is not the default.

a610ef8770ddfd `Adds flag for adjusting line height (not by default)`

Other related commits are

Switches from hhea to win :sob::
fec7b20 `Various improvements for mono-space generation`

Sets hhea-gap to zero:
9770856 `Zero out linegap values to allow power line glyphs to fill properly`

Here is a list of all _Code New Roman_ glyphs in the 'base range' that protrude out of the hhea/typo ascent-descent range.
They all protrude to the top (not bottom as assumed in 9770856).

I have no application that shows the original _Code New Roman_ in a correct way (i.e. A-ring `Å`within the allotted space), is there an application on Windows that (still) uses win instead of typo values?

```
Name            bb ymin  bb ymax
--------------------------------
Oslash             -215    1522
napostrophe           0    1559
Amacron               0    1616
Emacron               0    1616
Imacron               0    1616
Omacron             -18    1616
Umacron             -18    1616
bar                -410    1638
brokenbar          -410    1638
Aacute                0    1659
Acircumflex           0    1659
Adieresis             0    1659
Agrave                0    1659
Cacute              -16    1659
Ccaron              -16    1659
Ccircumflex         -16    1659
Dcaron                0    1659
Eacute                0    1659
Ecaron                0    1659
Ecircumflex           0    1659
Edieresis             0    1659
Egrave                0    1659
Gcircumflex         -18    1659
Hcircumflex           0    1659
Iacute                0    1659
Icircumflex           0    1659
Idieresis             0    1659
Igrave                0    1659
Jcircumflex           0    1659
Lacute                0    1659
Nacute                0    1659
Ncaron                0    1659
Oacute              -18    1659
Ocircumflex         -18    1659
Odieresis           -18    1659
Ograve              -18    1659
Ohungarumlaut       -18    1659
Racute                0    1659
Rcaron                0    1659
Sacute              -18    1659
Scaron              -18    1659
Scircumflex         -18    1659
Tcaron                0    1659
Uacute              -18    1659
Ucircumflex         -18    1659
Udieresis           -18    1659
Ugrave              -18    1659
Uhungarumlaut       -18    1659
Wcircumflex           0    1659
Yacute                0    1659
Ycircumflex           0    1659
Ydieresis             0    1659
Zacute                0    1659
Zcaron                0    1659
Abreve                0    1665
Ebreve                0    1665
Gbreve              -18    1665
Ibreve                0    1665
Obreve              -18    1665
Ubreve              -18    1665
Atilde                0    1671
Itilde                0    1671
Ntilde                0    1671
Otilde              -18    1671
Utilde              -18    1671
Cdotaccent          -16    1679
Edotaccent            0    1679
Gdotaccent          -18    1679
Idotaccent            0    1679
Zdotaccent            0    1679
hcircumflex           0    1710
lacute               -6    1720
Aring                 0    1740
Uring               -18    1740
```

**Comment by Finii** [comment]
Fixed via
* #1060

(and some following fixups)
