### ISSUE TITLE
Space Mono pre-patched font displays weird glyph for characters 'fl'

### ISSUE THREAD

**Issue by HuM4NoiD** [ryanoasis/nerd-fonts#477]
#### 🎯 Subject of the issue

The Characters f and l combine into a weird glyph, this only happens for lower case.
I needed a monotype font, so I installed mono variant.
Installing any other variant leads to non detection of the font when mono variants are strictly required
I have attached screenshots of Android Studio, VSCodium and Notepad.
I have installed mono variants of other fonts, none of them face such problems

#### 🔧 Your Setup

Installed pre-patched font Space Mono from downloads
`SpaceMono Nerd Font Mono` variant. [Link](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SpaceMono/Regular/complete/Space%20Mono%20Nerd%20Font%20Complete%20Mono.ttf)
VSCodium, Android Studio, Notepad
Windows 10

#### ★ Optional

![SpaceMonoError](https://user-images.githubusercontent.com/41481260/81707171-12ce5380-948e-11ea-8078-3e368a1539a0.png)

**Comment by hakamadare** [comment]
this seems similar to #469.

**Comment by fabricio7p** [comment]
Been having this issue with most nerd fonts... What's the proper workaround?

**Comment by polyzen** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/254#issuecomment-626362197

**Comment by HuM4NoiD** [comment]
Thank You I'll update once I have tried the fix

**Comment by Interesting-name** [comment]
Any news on how it worked out @HuM4NoiD?
I've been having the same issue, but was hesitant to mess around with fonts since I have no experience there.

**Comment by HuM4NoiD** [comment]
> Any news on how it worked out @HuM4NoiD?
> I've been having the same issue, but was hesitant to mess around with fonts since I have no experience there.
> 
> Edit: Also, this issue should be left open as it isn't yet fixed.

I downloaded the original Space Mono from Google Fonts, Copied the specified glyphs in FontForge (U+FB01, U+FB02) and deleted the next few glyphs, saved the edit as sfd. I will generate otf/ttf and then notify.

**Comment by ryanoasis** [comment]
Short term solution would seem to be not overwrite codepoints used for ligatures. Long term would be moving  codepoints 🤔

**Comment by Epholys** [comment]
I have a similar issue with the nerdfont-provided Ubuntu font: every `fi` ligature is displayed as `nf-mdi-phone_classic`. It drove me crazy because of course this ligature isn't used consistently :)

**Comment by AliMejbar** [comment]
Any update on this , the ligature is still showing incorrectly.

**Comment by Finii** [comment]
This should have been fixed by #711.

I'm not sure which files are patched with that PR in place, maybe the v2.2.0RC has them already, else please use the font files directly from the repo: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts

**Comment by KaranAhlawat** [comment]
Can confirm that the issue is fixed in the v2.2.0RC release. Although getting it directly from [https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts](url) did not work.

**Comment by nicolasshu** [comment]
Sorry, so what's the best way to fix this?

**Comment by KaranAhlawat** [comment]
> Sorry, so what's the best way to fix this?

Go to the releases page, download the v2.2.0RC or above, extract the package, and then copy the font to the desired location. That should be it.

**Comment by nulloneguy** [comment]
under "fi" also gives the symbol

**Comment by Finii** [comment]
All `fi` renders as phone should be fixed now with v2.2.1.
Please reopen if I err ;-)

**Comment by ayush-seth** [comment]
I am still facing this issue, I installed spacemono nerd font using homebrew. For example writing `amplify configure`
<img width="231" alt="image" src="https://user-images.githubusercontent.com/24858182/204080800-dcf8d519-35e1-467d-be48-cab36ccf9bc0.png">

I also installed jetbrains mono nerd font using homebrew and that works fine

**Comment by Finii** [comment]
~~Can you give the version of the file? Where you downloaded it?~~
Oh, you already gave it :grimacing: Let's see, I'm working on homebrew currently anyhow...

![image](https://user-images.githubusercontent.com/16012374/204081888-f3d546b0-85af-483e-aec8-8007c589b908.png)

Ah, you see the homebrew stuff has not been updated. This will be fixed together with #1003.
Currently the casks are not maintained by Nerd Fonts but by whoever has interest in maintaining :grimacing: 
Obviously noone had interest in updating SpaceMono.

I'm currently writing the stuff needed that we (i.e. Nerd Fonts) automatically maintains the casks.

**Comment by ayush-seth** [comment]
@Finii oh, sorry I should have checked the version in homebrew myself. Thank you for responding
