### ISSUE TITLE
Can't patch font "Cascadia Code PL".

### ISSUE THREAD

**Issue by rediffusion** [ryanoasis/nerd-fonts#512]
Aloha! 🙂

### 🔧 Your Setup

«Windows 10 2004»
Windows Terminal > WSL > Ubuntu-20.04

**Manual** has taken from Youtube tutorial "[Scott Hanselman](https://youtu.be/oHhiMf_6exY)".

---

### apt install python3-pip

# OUTPUT:

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> python3-pip is already the newest version (20.0.2-5ubuntu1).
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

### sudo apt-get install software-properties-common

# OUTPUT:

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> software-properties-common is already the newest version (0.98.9.1).
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

### sudo add-apt-repository ppa:fontforge/fontforge

# OUTPUT:

>  More info: https://launchpad.net/~fontforge/+archive/ubuntu/fontforge
> Press [ENTER] to continue or Ctrl-c to cancel adding it.
> 
> Ign:1 http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal InRelease
> Err:2 http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal Release
>   404  Not Found [IP: 91.189.95.83 80]
> Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
> Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

### sudo apt-get update

# OUTPUT:

> More info: https://launchpad.net/~fontforge/+archive/ubuntu/fontforge
> Press [ENTER] to continue or Ctrl-c to cancel adding it.
> 
> Ign:1 http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal InRelease
> Err:2 http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal Release
>   404  Not Found [IP: 91.189.95.83 80]
> Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
> Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> root@HOME-PC:/home/nika/nerd-fonts# sudo apt-get update
> Ign:1 http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
> Err:3 http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal Release
>   404  Not Found [IP: 91.189.95.83 80]
> Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
> Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/fontforge/fontforge/ubuntu focal Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

### sudo apt-get install fontforge

# OUTPUT:

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> fontforge is already the newest version (1:20190801~dfsg-4).
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

### fontforge -script font-patcher /mnt/c/Users/nika/Downloads/CascadiaCodePL.ttf -c

# OUTPUT:

Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 03:10 UTC  6-Mar-2020-ML-D-GDK3.
The following table(s) in the font have been ignored by FontForge
  Ignoring 'HVAR' horizontal metrics variations table
  Ignoring 'STAT' style attributes table
Use-my-metrics flag set on at least two components in glyph 681
Use-my-metrics flag set on at least two components in glyph 681
Use-my-metrics flag set on at least two components in glyph 713
Use-my-metrics flag set on at least two components in glyph 846
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Bad device table
Adding 54 Glyphs from Seti-UI + Custom Set
╢██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟ 4%font-patcher:823: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  glyph.left_side_bearing = 0.0
╢██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟ 4%Segmentation fault (core dumped)

**PLEASE PUT HERE FOR ME NORMAL MANUAL WHICH SHOWS ME AWERITHYNG STEP BY STEP.** Cheers! 👍👍👍

**Comment by tensor-programming** [comment]
Seeing the same thing on just the latest Cascadia Code even on my native linux Pop OS build.

**Comment by rediffusion** [comment]
@tensor-programming 

 Hmm... God knows what's this.

**Comment by aaronbell** [comment]
It looks like you are trying to patch the variable font version of Cascadia Code PL, which the patching script can’t deal with. 

I suggest using the static instances of the font instead (available in the “static” folder), either OTF or TTF.

**Comment by adrian5** [comment]
I can confirm what @aaronbell  wrote — the use of the variable font appears to be the cause.

Within the Cascadia Code release, instead of `ttf/CascadiaCode.ttf` you'll want to point the script to e.g. `ttf/static/CascadiaCode-Regular.ttf`. It's unfortunate that variable fonts aren't supported at the moment.

**Comment by sekti92** [comment]
I had the same issue. please tell me how to fix it?

**Comment by VPraharsha03** [comment]
> It looks like you are trying to patch the variable font version of Cascadia Code PL, which the patching script can’t deal with.

@aaronbell Is there a way to patch the variable fonts with custom glyphs? Strangely CMD/Powershell detects only them for me

**Comment by sekti92** [comment]
I fixed the issue by pointing at `otf/static/CascadiaCode-Regular.otf`

**Comment by aaronbell** [comment]
The variable font cannot be patched as the font patch code doesn’t understand how to process it. 

The only solution would be to add the glyphs in as part of the build process on our end, or for you to use the static versions instead.

**Comment by SuperHerp** [comment]
Even when i select the static font it still wont work 
`The requested file, original-source.otf, does not exist
Traceback (most recent call last):
  File "/home/simon/./font-patcher", line 939, in <module>
    main()
  File "/home/simon/./font-patcher", line 934, in main
    patcher.patch()
  File "/home/simon/./font-patcher", line 94, in patch
    symfont = fontforge.open(self.args.glyphdir + patch['Filename'])
OSError: Open failed
`

**Comment by Finii** [comment]
@SuperHerp I guess `original-source.otf` is not the name of the static Cascadia Code file you want to patch ;->

Can you give the command line you use together with something so show where the original files are?

**Comment by Finii** [comment]
This can obviously not be fixed as `fontforge` can not handle the font file.

It should not core-dump anymore, with recent `fontforges`
Added PR to issue a warning for users.

**Comment by Finii** [comment]
After the PR... add one explicit warning (pink) to all the fontforge warnings, that seem to be ignored :roll_eyes: (orange)

![image](https://user-images.githubusercontent.com/16012374/194848623-536b4b0e-3ca3-4777-ade7-8d1ba4e89cd0.png)

And because patching often just goes through (and creates a non-VF font), there is a warning in the end again:

![image](https://user-images.githubusercontent.com/16012374/194849537-9490ee8d-d300-478b-8057-d41bcecf3abb.png)
